"""add models

Revision ID: 58bdbf5247fe
Revises: 15b20a88e120
Create Date: 2021-11-11 17:28:32.464564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58bdbf5247fe'
down_revision = '15b20a88e120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userStatus',
    sa.Column('idUserStatus', sa.Integer(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idUserStatus')
    )
    op.drop_table('userstatus')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'userStatus', ['idUserStatus'], ['idUserStatus'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'userstatus', ['idUserStatus'], ['idUserStatus'])
    op.drop_constraint(None, 'user', type_='unique')
    op.create_table('userstatus',
    sa.Column('idUserStatus', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idUserStatus'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('userStatus')
    # ### end Alembic commands ###
