"""add models

Revision ID: a4b5d715bb21
Revises: 
Create Date: 2021-10-28 18:45:19.682536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4b5d715bb21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userStatus',
    sa.Column('idUserStatus', sa.Integer(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idUserStatus')
    )
    op.create_table('user',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=45), nullable=False),
    sa.Column('firstname', sa.VARCHAR(length=45), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=45), nullable=False),
    sa.Column('email', sa.VARCHAR(length=45), nullable=False),
    sa.Column('password', sa.VARCHAR(length=45), nullable=False),
    sa.Column('dateOfRegistration', sa.DateTime(), nullable=False),
    sa.Column('idUserStatus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idUserStatus'], ['userStatus.idUserStatus'], ),
    sa.PrimaryKeyConstraint('idUser')
    )
    op.create_table('article',
    sa.Column('idArticle', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('header', sa.VARCHAR(length=45), nullable=False),
    sa.Column('textOfArticle', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('idAuthor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idAuthor'], ['user.idUser'], ),
    sa.PrimaryKeyConstraint('idArticle')
    )
    op.create_table('modification',
    sa.Column('idModification', sa.Integer(), nullable=False),
    sa.Column('dateOfModification', sa.DateTime(), nullable=False),
    sa.Column('idUser', sa.Integer(), nullable=True),
    sa.Column('idArticle', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idArticle'], ['article.idArticle'], ),
    sa.ForeignKeyConstraint(['idUser'], ['user.idUser'], ),
    sa.PrimaryKeyConstraint('idModification')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modification')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('userStatus')
    # ### end Alembic commands ###
